CREATE TABLE IF NOT EXISTS `SUBSCRIBER`(
`id` INTEGER PRIMARY KEY ,
`name` VARCHAR(255) NOT NULL ,
`ref_tariff` VARCHAR( 10 ) NOT NULL);

CREATE TABLE IF NOT EXISTS `TARIFF`(
`id` INTEGER PRIMARY KEY,
`descr` VARCHAR(255) NOT NULL);

CREATE TABLE IF NOT EXISTS `PAYMENTS` (
`id` INTEGER PRIMARY KEY,
`ref_subscriber` INT ( 10 ) NOT NULL ,
`summa` INT( 10 ) NOT NULL);

